version: '3'

services:
  db:
    image: mysql:latest
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    user: 1000:1000
    volumes:
      - ./db:/var/lib/mysql:rw
    environment:                  
      MYSQL_ROOT_PASSWORD: django
      MYSQL_DATABASE: django-db
      MYSQL_USER: django
      MYSQL_PASSWORD: django
      TZ: 'Asia/Tokyo'

  web:
    build: ./python/
    container_name: python-django-opencv
    #command: python3 manage.py migrate
    command: python3 manage.py runserver 0.0.0.0:8080
    ports:
      - 8080:8080  
    volumes:
      - ./ar-web:/code
    ports:
      - 8080:8080
    depends_on:
      - db
